const char* UselessPhrases[] = 
{
    "With the power of gods, let's write the following:",
    "I smacked a damn big cockroach yesterday fella, this was left on my shoe:",
    "Don't distract fella, I don't know how to count",
    "Oh come on, my wife is pregnant 12th time in a row.",
    "Can you understand it by yourself, i must go get some beer, fella:",
    "...",
    "Thanks man",
    "I don't fucking know how this expression was calculated, fella, i am a cowboy",
    "By the way our existence is nonsence, think about it fella",
    "Go get yourself a beer, it would be a long road",
    "Fucking hell, I will go, this is too fucking boring",
   "Hold my beer son, i will handle this one",
    "Hey fella, i think it is too difficult to understand",
    "Wanna try it yourself lazy shit?",
    "Ok, ok. We, western cowboys handle such things every day",
    "Well, no clue how to simplificate this shit",
    "Let's just shoot some niggers, running down the road",
    "I forgot to tell you, i don't know math, i am a fucking cowboy, fella",
};